In [1]:
#Load Library
import numpy as np

In [2]:
#Creating Matrix 1-D
#Create a vector as a Row
vector_row = np.array([1,2,3])
vector_row

array([1, 2, 3])

In [4]:
#Create vector as a Column
vector_column = np.array([[1],[2],[3]])
vector_column

array([[1],
       [2],
       [3]])

In [5]:
#Create 2-DMatrix
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [6]:
#Creating Sparse MAtrix (mostly Zeros)
matrix = np.array([[0,0],[0,1],[3,0]])
print(matrix)

[[0 0]
 [0 1]
 [3 0]]


In [11]:
#Create Compressed Sparse Row(CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

NameError: name 'sparse' is not defined

In [14]:
#Select element from a matrix
#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
#Create a vector as a Row
vector_row = np.array([ 1,2,3,4,5,6 ])
#Select 3rd element of Vector
print(vector_row[2])
#Select 2nd row 2nd column
print(matrix[1,1])
#Select all elements of a vector
print(vector_row[:])
#Select everything up to and including the 3rd element
print(vector_row[:3])
#Select the everything after the 3rd element
print(vector_row[3:])
#Select the last element
print(vector_row[-1])
#Select the first 2 rows and all the columns of the matrix
print(matrix[:2,:])
#Select all rows and the 2nd column of the matrix
print(matrix[:,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
5
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6
[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]


In [18]:
#DESCRIBE A MATRIX
#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print("***********************************************************")
#View the Number of Rows and Columns
print(matrix.shape)
print("***********************************************************")
#View the number of elements (rows*columns)
print(matrix.size)
print("***********************************************************")
#View the number of Dimensions(2 in this case)
print(matrix.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***********************************************************
(3, 3)
***********************************************************
9
***********************************************************
2


In [19]:
#Applying operations to elements

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print("***********************************************************")

#Create a function that adds 100 to something
add_100 =lambda i: i+100
#Convert it into a vectorized function
vectorized_add_100= np.vectorize(add_100)
#Apply function to all elements in matrix
print(vectorized_add_100(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***********************************************************
[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [20]:
#Finding the max and min values

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print("***********************************************************")
#Return the max element
print(np.max(matrix))
print("***********************************************************")
#Return the min element
print(np.min(matrix))
print("***********************************************************")
#To find the max element in each column
print(np.max(matrix,axis=0))
print("***********************************************************")
#To find the max element in each row
print(np.max(matrix,axis=1))#cumulative
print("***********************************************************")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***********************************************************
9
***********************************************************
1
***********************************************************
[7 8 9]
***********************************************************
[3 6 9]
***********************************************************


In [21]:
#Calculating Average, Variance and Standard deviation

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print("***********************************************************")
#Mean
print(np.mean(matrix)) #sum of numbers/len(length of numbers)
print("***********************************************************")
#Standard Dev.
print(np.std(matrix))
print("***********************************************************")
#Variance
print(np.var(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***********************************************************
5.0
***********************************************************
2.581988897471611
***********************************************************
6.666666666666667


In [23]:
#Reshaping Arrays

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print("***********************************************************")
#Reshape
print(matrix.reshape(9,1))
print("***********************************************************")
#Here -1 says as many columns as needed and 1 row
print(matrix.reshape(1,-1))
print("***********************************************************")
#If we provide only 1 value Reshape would return a 1-d array of that length
print(matrix.reshape(9))
print("***********************************************************")
#We can also use the Flatten method to convert a matrix to 1-d array
print(matrix.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***********************************************************
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
***********************************************************
[[1 2 3 4 5 6 7 8 9]]
***********************************************************
[1 2 3 4 5 6 7 8 9]
***********************************************************
[1 2 3 4 5 6 7 8 9]


In [24]:
#Transposing a vector or a Matrix
#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print("***********************************************************")
#Transpose the matrix
print(matrix.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***********************************************************
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [25]:
#Finding the Determinant and Rank of a Matrix
#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print("***********************************************************")
#Calculate the Determinant
print(np.linalg.det(matrix))
print("***********************************************************")
#Calculate the Rank
print(np.linalg.matrix_rank(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***********************************************************
-9.51619735392994e-16
***********************************************************
2


In [26]:
# Getting the Diagonal of a Matrix

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print("***********************************************************")
#Print the Principal diagonal
print(matrix.diagonal())
print("***********************************************************")
#Print the diagonal one above the Principal diagonal
print(matrix.diagonal(offset=1))
print("***********************************************************")
#Print the diagonal one below Principal diagonal
print(matrix.diagonal(offset=-1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***********************************************************
[1 5 9]
***********************************************************
[2 6]
***********************************************************
[4 8]


In [30]:
#Calculating the trace of a Matrix (Sum of the diagnol)
#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print("***********************************************************")
#Print the Trace
print(matrix.trace(
   # offset=1
))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***********************************************************
15


In [32]:
# Finding Eigenvalues and Eigenvectors -->Change only in scale(not direction)

#A*v =K*v #A square matrix ,K contains eigenvlaues and v contains eigenvectors

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print("***********************************************************")
# Calculate the Eigenvalues and Eigenvectors of that Matrix
eigenvalues ,eigenvectors=np.linalg.eig(matrix)
print(eigenvalues)
print("***********************************************************")
print(eigenvectors)
print("***********************************************************")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
***********************************************************
[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
***********************************************************
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
***********************************************************


In [33]:
#Calculating Dot Products
#Create vector-1
vector_1 = np.array([ 1,2,3 ])
print(vector_1)
print("***********************************************************")
#Create vector-2
vector_2 = np.array([ 4,5,6 ])
print(vector_2)
print("***********************************************************")
#Calculate Dot Product
print(np.dot(vector_1,vector_2))
print("***********************************************************")
#Alternatively you can use @ to calculate dot products
print(vector_1 @ vector_2)

[1 2 3]
***********************************************************
[4 5 6]
***********************************************************
32
***********************************************************
32


In [34]:
#Adding, Subtracting and Multiplying Matrices

#Create Matrix-1
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix_1)
print("***********************************************************")
#Create Matrix-2
matrix_2 = np.array([[7,8,9],[4,5,6],[1,2,3]])
print(matrix_2)
print("***********************************************************")
#Add the 2 Matrices
print(np.add(matrix_1,matrix_2))
print("***********************************************************")
#Subtraction
print(np.subtract(matrix_1,matrix_2))
print("***********************************************************")
#Multiplication(Element wise, not Dot Product)
print(matrix_1*matrix_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***********************************************************
[[7 8 9]
 [4 5 6]
 [1 2 3]]
***********************************************************
[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]
***********************************************************
[[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]]
***********************************************************
[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]


In [36]:
#Inverting a Matrix (the inverse of a Square Matrix)
#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print("***********************************************************")
#Calculate its inverse
print(np.linalg.inv(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***********************************************************
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [37]:
#Generating Random values
#Set seed
np.random.seed(1)
#Generate 3 random integers b/w 1 and 10
print(np.random.randint(0,11,3))
#Draw 3 numbers from a normal distribution with mean 1.0 and std 2.0
print(np.random.normal(1.0,2.0,3))

[5 8 9]
[-0.60434568  0.10224438 -1.21187015]
